export const products = [
  {
    id: 1,
    name: "Banshee Gundam GS-Toys - GLADIATOR TYPE I - Asa.Ka",
    image: require("../Assets/sanpham1.jpg"),         
    hoverImage: require("../Assets/s1.jpg"),   
    price: 63.99,
    oldPrice: 79.99,
    stock: false,
  },
  {
    id: 2,
    name: "Barbatos Lupus Bộ phụ kiện tay - Baki Arm",
    image: require("../Assets/sanpham2.jpg"),
    hoverImage: require("../Assets/s2.jpg"),   
    scale: "1/100 MG",
    price: 32.99,
    sale: true,
  },
  {
    id: 3,
    name: "Destiny SC-009 — DIVINE INVOKER·PERCIVAL ( Deluxe Version )",
    image: require("../Assets/sanpham3.jpg"),
    hoverImage: require("../Assets/s3.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 4,
    name: "CD-TG03 Tianchen",
    image: require("../Assets/sanpham4.jpg"),
    hoverImage: require("../Assets/s4.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 5,
    name: "Tyran Power Mecha - Impulse Gundam Ver.Resin",
    image: require("../Assets/sanpham5.jpg"),
    hoverImage: require("../Assets/s5.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 6,
    name: "Sky Demon",
    image: require("../Assets/sanpham6.jpg"),
    hoverImage: require("../Assets/s6.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 7,
    name: "1/100 Rx78-2 Gundam ver RG 2.0 (09 Dragon)",
    image: require("../Assets/sanpham7.jpg"),
    hoverImage: require("../Assets/s7.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 8,
    name: "MG Astray Red Frame New Ver.",
    image: require("../Assets/sanpham8.jpg"),
    hoverImage: require("../Assets/s8.jpg"),
    scale: "1/144 HG",
    price: 48.99,
    new: true,
  },
  {
    id: 9,
    name: "Uy Viễn Thức - Hoả Chiến ",
    image: require("../Assets/sanpham9.jpg"),
    hoverImage: require("../Assets/s9.jpg"),
    scale: "1/100 MG",
    price: 48.99,
    new: true,
  },
  {
    id: 10,
    name: "I Am Great Hero",
    image: require("../Assets/sanpham10.jpg"),
    hoverImage: require("../Assets/s10.jpg"),
    scale: "13.5cm",
    price: 48.99,
    new: true,
  },
  {
    id: 11,
    name: "MCT - AP02 WUCHENG - DARK VER.",
    image: require("../Assets/sanpham11.jpg"),
    hoverImage: require("../Assets/s11.jpg"),
    scale: "1/72",
    price: 48.99,
    new: true,
  },
  {
    id: 12,
    name: "Falcon Darkstar",
    image: require("../Assets/sanpham12.jpg"),
    hoverImage: require("../Assets/s12.jpg"),
    scale: "1/100 MG",
    price: 48.99,
    new: true,
  },
];
